export default function Footer() {
  return (
    <footer
      className="mt-auto relative overflow-hidden"
      style={{
        background: 'linear-gradient(180deg, transparent 0%, rgba(10, 10, 15, 0.8) 100%)',
        borderTop: '1px solid rgba(0, 245, 255, 0.1)',
      }}
    >
      {/* Decorative gradient line */}
      <div 
        className="absolute top-0 left-0 right-0 h-px"
        style={{
          background: 'linear-gradient(90deg, transparent 0%, var(--neon-cyan) 50%, transparent 100%)',
          opacity: 0.5,
        }}
      />
      
      <div className="container mx-auto px-4 py-8">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          {/* Logo & Copyright */}
          <div className="text-center md:text-left">
            <p
              className="font-bold text-lg mb-1"
              style={{
                fontFamily: "'Playfair Display', serif",
              }}
            >
              <span className="gradient-text">Board</span>
              <span style={{ color: 'var(--neon-gold)' }}>Saga</span>
            </p>
            <p
              className="text-sm"
              style={{
                color: 'var(--moon-glow)',
                opacity: 0.7,
              }}
            >
              &copy; {new Date().getFullYear()} BoardSaga. Turning moves into myths.
            </p>
          </div>

          {/* Disclaimer */}
          <div className="text-center md:text-right max-w-md">
            <p
              className="text-xs"
              style={{
                color: 'var(--moon-glow)',
                opacity: 0.6,
                lineHeight: '1.6',
              }}
            >
              Stories generated by AI with Stockfish engine analysis. 
              <br />
              AI may occasionally make mistakes.
            </p>
          </div>
        </div>

        {/* Bottom decorative elements */}
        <div className="flex justify-center gap-2 mt-6">
          {[...Array(5)].map((_, i) => (
            <div
              key={i}
              className="w-1 h-1 rounded-full"
              style={{
                background: i === 2 ? 'var(--neon-gold)' : 'var(--neon-cyan)',
                opacity: i === 2 ? 1 : 0.5,
                boxShadow: i === 2 ? '0 0 10px var(--neon-gold)' : 'none',
              }}
            />
          ))}
        </div>
      </div>
    </footer>
  )
}
